database = off
declarative_config = /etc/kong/kong.yml

proxy_listen = 0.0.0.0:80, 0.0.0.0:443 ssl
admin_listen = 127.0.0.1:8001

router_flavor = expressions

nginx_http_include = /etc/kong/nginx.conf
