server {
    listen 8101;
    server_name _;

    ssl_certificate /etc/kong/ssl/kong-default.crt;
    ssl_certificate_key /etc/kong/ssl/kong-default.key;

    root /var/www/frontend;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
